# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26939a996dadb42654c2878cb9d5aacb7a872714c21cb3cf026db894232cd3c8b9e4e1b258a19e8b8edce890eeb6a2ebb26a19e6f5eef7eb6aa09e90b41026b

test:
  secret_key_base: fb1bae9ac78949ca2d3c96eb42fab455504fe3c057506a12d11d12a57f3b4145dc560d0706c40afed0650f17c65e8b816a31a2d68157d9c9d4d64d02f292dda4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
